const ROLE_STUDENT = 'STUDENT';
const ROLE_SUPER_ADMIN = 'SUPER_ADMIN';
const ROLE_ADMIN = 'ADMIN';
const ROLE_ASSISTANT = 'ASSISTANT';
const ROLE_LECTURER = 'LECTURER';


module.exports = {
    ROLE_ADMIN,
    ROLE_SUPER_ADMIN,
    ROLE_STUDENT,
    ROLE_LECTURER,
    ROLE_ASSISTANT
};